name: ESLint Check

on:
  workflow_call:
    inputs:
      # reporter:
      #   required: true
      #   type: string
      # fail_on_error:
      #   required: true
      #   type: boolean
      # eslint_flags:
      #   required: true
      #   type: string
      # workdir:
      #   required: true
      #   type: string
      config_path:
        required: true
        type: string
      ignore_path:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Retrieve Prepared Repository
        uses: actions/download-artifact@v2
        with:
          name: setup-app

      - name: Unzip Artifact
        run: unzip app.zip

      # - name: Run ESLint
      #   uses: reviewdog/action-eslint@v1.14.0
      #   with:
      #     reporter: ${{ inputs.reporter }}
      #     github_token: ${{ secrets.token }}
      #     fail_on_error: ${{ inputs.fail_on_error }}
      #     eslint_flags: ${{ inputs.eslint_flags }}
      #     workdir: ${{ inputs.workdir }}

      - name: Run ESLint
        run: npx eslint -c ${{ inputs.config_path }} --ignore path ${{ inputs.ignore_path }} --output-file eslint_report.txt

      - name: ESLint Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo eslint_report.txt
