name: Production CI/CD

on:
  release:
    types: [released]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: production

jobs:
  build:
    uses: rutajdash/actions-test-repo/.github/workflows/build.yml@main
    with:
      node_env: ${{ env.NODE_ENV }}
      image_name: ${{ env.IMAGE_NAME }}
      registry: ${{ env.REGISTRY }}
      context: .
      dockerfile: ./Dockerfile
      is_latest: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    uses: rutajdash/actions-test-repo/.github/workflows/deploy.yml@main
    with:
      node_env: ${{ env.NODE_ENV }}
      ssh_hosts: ${{ secrets.SSH_HOSTS }}
      ssh_username: mm
      image_name: ${{ env.IMAGE_NAME }}
      registry: ${{ env.REGISTRY }}
    secrets:
      env_vars: ${{ secrets.PROD_ENV }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
