name: Staging CI/CD

on:
  push:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run Prettier
        uses: rutajdash/prettier-cli-action@cbb0a59de4684855faf5154e84870fbffedb12fe
        with:
          config_path: './.prettierrc.yml'
