name: Staging CI/CD

on:
  push:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  setup:
    uses: rutajdash/actions-test-repo/.github/workflows/setup.yml@main
    with:
      setup_dev: true

  eslint:
    needs: setup
    uses: rutajdash/actions-test-repo/.github/workflows/eslint.yml@main
    with:
      config_path: ./.eslintrc.yml
      ignore_path: ./.eslintignore
    #   reporter: github-check
    #   fail_on_error: true
    #   eslint_flags: ''
    #   workdir: ${{ github.workspace }}
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    needs: setup
    uses: rutajdash/actions-test-repo/.github/workflows/prettier.yml@main
    with:
      file_pattern: '.'
      config_path: './.prettierrc.yml'
      ignore_path: './.prettierignore'
      fail_on_error: true
