name: Staging CI/CD

on:
  push:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: staging

jobs:
  setup:
    uses: rutajdash/actions-test-repo/.github/workflows/setup.yml@main
    with:
      setup_dev: true

  eslint:
    needs: setup
    uses: rutajdash/actions-test-repo/.github/workflows/eslint.yml@main
    with:
      reporter: github-check
      fail_on_error: true
      eslint_flags: 'server/'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    needs: setup
    uses: rutajdash/actions-test-repo/.github/workflows/prettier.yml@main
    with:
      file_pattern: './server/.'
      config_path: './.prettierrc.yml'
      ignore_path: './.prettierignore'
      fail_on_error: true

  mocha:
    needs: [eslint, prettier]
    uses: rutajdash/actions-test-repo/.github/workflows/mocha.yml@main

  build:
    needs: mocha
    uses: rutajdash/actions-test-repo/.github/workflows/build.yml@main
    with:
      node_env: ${{ env.NODE_ENV }}
      image_name: ${{ env.IMAGE_NAME }}
      registry: ${{ env.REGISTRY }}
      context: .
      dockerfile: ./Dockerfile
      is_latest: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
