name: Staging CI/CD

on:
  push:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@3e0ea71aee9c4a8dc6f2b13f6ba050ff9291a4ba
        with:
          config_path: ./.prettierrc.yml

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: echo "The following files are not formatted:${{steps.prettier-run.outputs.prettier_output}}"
